# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [23]:
import numpy as np
arr = np.array(range(0,10))
arr = arr.reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [24]:
arr1= np.arange(10).reshape(2,5)
arr1
arr2 = np.ones(10).astype(np.int).reshape(2,5)
arr2
arr3 = np.vstack((arr1,arr2))
arr3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [25]:
arr4 = np.hstack((arr1,arr2))
arr4

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [30]:
a = np.arange(10).reshape(2,5)
a = a.flatten()
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [35]:
array = np.arange(15).reshape(3,5)
array = np.ravel(array)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [39]:
array = np.arange(15).reshape(5,3)
array


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [69]:
array = np.random.randn(5,5)*10
array = array.astype(np.int)
array = np.square(array)
array

array([[ 36,   1,  16,  36,  16],
       [  1,   9, 144,  81, 256],
       [225,   0,  81,   0,   4],
       [441,   0,  25,  49,   0],
       [ 25, 196,   9,   1,   0]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [70]:
array  = np.random.randn(5,6)*10
array = array.astype(np.int)
print(array)
array.mean()

[[  2   1   1  -9 -13 -19]
 [-11   8   1   8   3   0]
 [ -8  -2   0   2  12  -3]
 [  6  -6   6   8   5   0]
 [  1  11  12  -3  -7   0]]


0.2

## Question:9

### Find the standard deviation of the previous array in Q8?

In [71]:
array.std()

7.350283441246784

## Question:10

### Find the median of the previous array in Q8?

In [72]:
np.median(array)

1.0

## Question:11

### Find the transpose of the previous array in Q8?

In [73]:
array.transpose()

array([[  2, -11,  -8,   6,   1],
       [  1,   8,  -2,  -6,  11],
       [  1,   1,   0,   6,  12],
       [ -9,   8,   2,   8,  -3],
       [-13,   3,  12,   5,  -7],
       [-19,   0,  -3,   0,   0]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [87]:
array = np.random.randn(4,4)*10
array.astype(np.int)
np.trace(array)


16.828859727851714

## Question:13

### Find the determinant of the previous array in Q12?

In [88]:
from numpy.linalg import inv, qr
print(np.linalg.det(array))

5314.451828063812


## Question:14

### Find the 5th and 95th percentile of an array?

In [92]:
array  = np.random.randn(5,5)*10
array.astype(np.int)
print("5th Percentile is : " ,np.percentile(array,5))
print("95th Percentile is : " ,np.percentile(array,95))

5th Percentile is :  -16.23157515791696
95th Percentile is :  12.052262483218936


## Question:15

# How to find if a given array has any null values?